<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
        <li>
        <i class="icon-home home-icon"></i>
        <a href="/admin/dashboard">Home</a>
        </li>

        <li>
        <a href="/admin/user" class="active">User List</a>
        </li>
    </ul><!-- .breadcrumb -->

    <div class="nav-search" id="nav-search">
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
    </div><!-- #nav-search -->
</div>

<div class="page-content">

    <div class="row">
        <div class="col-xs-12">
            <h3 class="header smaller lighter blue">
                User List
                <a href="/admin/user/create" class="btn btn-sm"><i class="icon-user align-top bigger-125"></i> Create New</a>
            </h3>
            <div class="table-header">
                Showing <?=$pager->offset_start?> to <?=$pager->offset_end?> of <?=$pager->total_items?> Items
            </div>

            <div class="table-responsive dataTables_wrapper">
                <div class="row">
                    <div class="col-sm-12">
                        <form class="form-inline">
                            <div class="form-group">
                                <?=$form->render('uid', array(
                                    'placeholder' => 'ID',
                                    'class' => 'form-control input-sm'
                                ))?>
                            </div>
                            <div class="form-group">
                                <?=$form->render('username', array(
                                    'placeholder' => 'Username',
                                    'class' => 'form-control input-sm autocomplete',
                                    'data-autocomplete-source' => '/admin/user/process/suggestions?query=%QUERY',
                                    'data-autocomplete-target' => 'input[name=uid]',
                                    'data-autocomplete-fill-name' => 'id',
                                    'data-autocomplete-display-key' => 'username',
                                ))?>
                            </div>
                            <div class="form-group">
                                <?=$form->render('email', array(
                                        'placeholder' => 'email',
                                        'class' => 'form-control input-sm'
                                    ))?>
                            </div>
                            <div class="form-group">
                                <?=$form->render('status', array(
                                    'class' => 'form-control input-sm'
                                ))?>
                            </div>
                           <span>
                                <label for="filter-from-limit">Display</label> 
                            </span>
                            <div class="form-group">
                                <?=$form->render('limit', array(
                                    'class' => 'form-control input-sm'
                                ))?>
                            </div>
                            <button class="btn btn-info btn-sm form-control" type="submit">
                                <i class="icon-search bigger-110"></i>
                                Filter 
                            </button>
                        </form>

                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover dataTable table-sortable" id="post-grid"  data-sortable-key="order" data-sortable-default="-id">
                    <thead>
                        <tr>
                            <th class="center">
                                <label>
                                    <input type="checkbox" class="ace">
                                    <span class="lbl"></span>
                                </label>
                            </th>
                            <th class="hidden-480">
                                <a href="<?=$this->tag->uri('/admin/user', $pager->query)?>" class="sortable-link" data-sortable-value="id">ID</a>
                            </th>
                            <th>
                                <a href="<?=$this->tag->uri('/admin/user', $pager->query)?>" class="sortable-link" data-sortable-value="username">Username</a>
                            </th>
                            <th class="hidden-480">Status</th>
                            <th>Email</th>
                            <th>Register Source</th>
                            <th>
                                <a href="<?=$this->tag->uri('/admin/user', $pager->query)?>" class="sortable-link" data-sortable-value="created_at" data-sortable-default="-created_at">
                                    <i class="icon-time bigger-110"></i>
                                    Register Time 
                                </a>
                            </th>
                            <th>
                                <i class="icon-time bigger-110"></i>
                               Last Login 
                            </th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        <?foreach($pager->items as $item):?>
                        <tr>
                            <td class="center">
                                <label>
                                    <input type="checkbox" class="ace" value="<?=$item->id?>"  data-batch-source="<?=$item->id?>">
                                    <span class="lbl"></span>
                                </label>
                            </td>
                            <td class="hidden-480"><?=$item->id?></td>
                            <td>
                                <a href="/admin/user/edit/<?=$item->id?>">
                                    <?=$item->username?>
                                    <?if($item->screenName):?>
                                    (<?=$item->screenName?>)
                                    <?endif?>
                                </a>
                                <?if($this->moduleManager->hasModule('EvaPermission') && $item->roles):?>
                                <?foreach($item->roles as $role):?>
                                <button class="btn btn-xs btn-info ajax-form-sumbit" data-ajax-form="1" date-method="delete" data-form-action="/admin/permission/process/user/<?=$item->id?>/role/<?=$role->id?>" data-callback="form.remove();">
                                    <?=$role->name?> <?=$role->roleKey?> <i class="icon-remove bigger-120"></i> 
                                </button>
                                <?endforeach;?>
                                <?endif?>
                            </td>
                            <td class="hidden-480">
                                <?$status = array(
                                    'inactive' => 'label-warning',
                                    'deleted' => 'label',
                                    'active' => 'label-success',
                                )?>
                                <span class="label label-sm <?=$status[$item->status]?>"><?=$item->status?></span>
                                <span class="label label-sm <?=$status[$item->emailStatus]?>"><i class="icon-envelope"></i> <?=$item->emailStatus?></span>
                            </td>
                            <td><?=$item->email?></td>
                            <td><?=$item->providerType?></td>
                            <td><?=$this->tag->datetime($item->createdAt)?></td>
                            <td><?=$item->loginAt ? $this->tag->datetime($item->loginAt) : 'Never'?></td>
                            <td>
                                <div class="btn-group">
                                    <button class="btn btn-xs btn-success ajax-form-sumbit" data-ajax-form="1" date-method="put" data-form-action="/admin/user/process/status/<?=$item->id?>" data-callback="window.location.reload();">
                                        <input type="hidden" data-name="status" value="active" >
                                        <i class="icon-ok bigger-120"></i>
                                    </button>

                                    <a class="btn btn-xs btn-info" href="/admin/user/edit/<?=$item->id?>">
                                        <i class="icon-edit bigger-120"></i>
                                    </a>

                                    <button class="btn btn-xs btn-warning ajax-form-sumbit" data-ajax-form="1" date-method="put" data-form-action="/admin/user/process/status/<?=$item->id?>" data-callback="window.location.reload();">
                                        <input type="hidden" data-name="status" value="deleted" >
                                        <i class="icon-eye-close bigger-120"></i>
                                    </button>

                                    <button class="btn btn-xs btn-danger ajax-form-sumbit" data-ajax-form="1" date-method="delete" data-form-action="/admin/user/process/delete/<?=$item->id?>" data-confirm="1" data-confirm-message="<?=sprintf('User %s will be deleted, are you sure?', $item->username)?>" data-callback="form.closest('tr').hide();">
                                        <i class="icon-trash bigger-120"></i>
                                    </button>

                                    <?if($this->moduleManager->hasModule('EvaPermission')):?>
                                    <a class="btn btn-xs btn-info" href="/admin/permission/apikey/create?uid=<?=$item->id?>">
                                        <i class="icon-key bigger-120"></i>
                                    </a>
                                    <?endif?>
                                </div>
                            </td>
                        </tr>
                        <?endforeach?>
                    </tbody>
                </table>

                <div class="row">
                    <div class="col-sm-6">
                        <div class="btn-group">
                            <button class="btn btn-xs btn-success ajax-form-sumbit" data-batch-form="1" data-source-name="id" data-source-selectors="#post-grid input[data-batch-source]" date-method="put" data-form-action="/admin/post/batch" data-callback="window.location.reload();">
                                <input type="hidden" data-name="status" value="published" >
                                <i class="icon-ok bigger-120"></i>
                            </button>

                            <button class="btn btn-xs btn-warning ajax-form-sumbit" data-batch-form="1" data-source-name="id" data-source-selectors="#post-grid input[data-batch-source]" date-method="put" data-form-action="/admin/post/batch" data-callback="window.location.reload();">
                                <input type="hidden" data-name="status" value="deleted" >
                                <i class="icon-eye-close bigger-120"></i>
                            </button>

                            <?if($this->moduleManager->hasModule('EvaPermission')):?>
                            <?$roles = \Eva\EvaPermission\Entities\Roles::find();?>
                            <?foreach($roles as $role):?>
                            <button class="btn btn-xs btn-info ajax-form-sumbit" data-batch-form="1" data-source-name="id" data-source-selectors="#post-grid input[data-batch-source]" date-method="put" data-form-action="/admin/permission/process/applyroles" data-callback="window.location.reload();">
                                <i class="icon-key bigger-120"></i>
                                <input type="hidden" data-name="roleId" value="<?=$role->id?>" ><?=$role->roleKey?> <?=$role->name?>
                            </button>
                            <?endforeach;?>
                            <?endif?>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="dataTables_paginate">
                            <?$this->partial("partial/paginator", array(
                                'pagerUrl' => '/admin/user',
                                'pager' => $pager,
                            ))?>
                        </div>
                    </div>
                </div>

            </div><!--/table div-->

        </div><!-- /col-->
    </div><!--row end-->

</div><!-- /.page-content -->
